### ISSUE TITLE
More parameters for profile URL

### ISSUE THREAD

**Issue by cadorn** [openpeer/opios#237]
This is what the profile URL log looks like now:

````
188.2.90.142 - - [12/Mar/2014:16:32:11 +0000] "GET /itunes-appstore/config.json HTTP/1.1" 200 434 "-" "openpeersample/1.12 CFNetwork/672.0.8 Darwin/14.0.0"
188.2.90.142 - - [12/Mar/2014:16:33:54 +0000] "GET /itunes-appstore/config.json HTTP/1.1" 200 434 "-" "openpeersample/1.12 CFNetwork/672.0.8 Darwin/14.0.0"
188.2.90.142 - - [12/Mar/2014:16:42:56 +0000] "GET /itunes-appstore/config.json HTTP/1.1" 200 434 "-" "openpeersample/1.12 CFNetwork/672.0.8 Darwin/14.0.0"
````

We need to include a build or version number.

When configuring the profile url you should be able to set something like `http://profiles.hookflash.com/itunes-appstore/config.json?build=%BUILD%` where the app replaces `%BUILD%` with its build number before calling url.

This is essential for us to see which builds are installed and still active.

**Comment by SergioOpenPeer** [comment]
It is used this concept http://profiles.hookflash.com/build/build_number/config.json
