### ISSUE TITLE
Shutting down SDK when login is progress -- how to close webviews?

### ISSUE THREAD

**Issue by arasbm** [openpeer/opios#325]
In the test app I am developing, I have a button to shutdown and initialize the SDK on demand, so that when a test fails, we can quickly restart the SDK in a fresh state without having to restart the whole app. This seems to work for the most part, but if login is in progress and webview associated with `LoginDelegate` is being displayed, at the time shutdown happens, I dont know how to properly close the webview so that login will start clean next time SDK is initialized. I suspect the problem may be that `HOPIdentityStateShutdown` is not triggered during shutdown, so inside the `IdentityDelegate.m` we have:

```
            case HOPIdentityStateShutdown:
            {
                // this is not called when shutting down the SDK
            }
```

I am guessing, if that delegate fires, I would be able to safely remove any visible webview. So my question is, should I expect to be able to shutdown and re-initialize SDK on demand and get it working again? If so, where would be the best place to take remove any visible webview for login that is pending when shutdown occurs.

cc @SergioOpenPeer @robin-raymond 

related to https://github.com/hookflashco/hcs-stack-cordova/issues/14

**Comment by SergioOpenPeer** [comment]
Best place for that case would be inside IdentityDelegate.m under case HOPIdentityStateShutdown:
