### ISSUE TITLE
One app is getting open peer contacts from the other app

### ISSUE THREAD

**Issue by SergioOpenPeer** [openpeer/opios#363]
On opp.me for release@hokflash.com mail, it is created a new Facebook app com.hooflash.sample. This is the only app for this account. 
On one device Ilija.Cvorovic@usa.com is logged in. This mail is used also for login in some other Facebook apps but for other account, not for release@hookflash.com. Once contacts are loaded I get that all of them are open peer contacts.
On another device Sergej.vilotic@yahoo.com is logged in and he gets that only Ilija.Cvorovic@usa.com is open peer contact (what is true), and all other contacts, event some of them are shared with Ilija.Cvorovic@usa.com, are not.
Same app, different users, but get different statuses for the same contacts.

**Comment by cadorn** [comment]
Assumed fixed.
