### ISSUE TITLE
Update device token owner on server side

### ISSUE THREAD

**Issue by SergioOpenPeer** [openpeer/opios#375]
Once another user is logged in in our application on same device it is necessary on server side to map peer URI of newly logged in user to existing device token, and to remove previous mapping.

So logic behind http://push-hack.hcs-stack-v2-i7957106-7.hcs.io/device-associate-set should be updated

**Comment by cadorn** [comment]
Push hack source code: https://github.com/openpeer/hcs-server-push-hack-nodejs

**Comment by cadorn** [comment]
@SergioOpenPeer Can you please include a sample request in this issue.

Are there logs for push-hack calls? Can you include some?

**Comment by cadorn** [comment]
Spec: https://github.com/openpeer/hcs-system/blob/master/architecture/client/Push%20Hack%20-%20Protocol%20Specification.md

**Comment by cadorn** [comment]
After spec if updated, create new doc at http://mdocs.hookflash.com/ and use hyperlink to new API call in JS API docs like so: https://github.com/openpeer/hcs-server-push-hack-nodejs/blob/master/server-test.js#L36

**Comment by cadorn** [comment]
$feature https://github.com/hookflashco/hookflash.me/issues/7

**Comment by SergioOpenPeer** [comment]
{"request":{"deviceToken":"d05e2ddd97cdfbbf746538004e53ce58d4dfc4fef7656446cdf49ff2827fe1bb","type":"apns","$domain":"com-hookflash-sampleapp.app.hcs.io","$handler":"push-hack","$id":"07B59759-8490-4F16-9AB4-1F6A3D493D53","$method":"device-associate-set","uri":"peer:\/\/hcs.io\/5385660b16765b3f05677dcd8e9a433f5ac64e1ca7739bf97c816e3dc2902423","$appid":"com.hookflash.sampleapp"}}

url: http://push-hack.hcs-stack-v2-i7957106-7.hcs.io/device-associate-set
